name: Nissa Szabo
title:
email: nissa.szabo@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
baseurl: ""
url: "https://nissaszabo.com"
twitter_username: nisszab
github_username:  nszabo

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
